### PR TITLE
Stubbs Lab week 2

### PR DESCRIPTION
**Pull request by jas58**
examples of editing csv then pushing to remote

### CODE REVIEW

**Comment by jas58** [comment]
Why does my file not conflict?

**Comment by chrisdaaz** [comment]
looks good! why do you think the file would conflict?

**Comment by jas58** [comment]
Thanks for asking.
I know my changes to the rows are different from classmates' changes.  So only one version of the spreadsheet data will be harvested from the main/origin.  Unless someone specifically wanted the data from a specific version of the branches.
I think I'm still lost by when a branch will be merged, or whose branch would come out on top at the end. Perhaps it's that these pull requests are not automating any later steps (such as when or which may merge with main/origin)--is that correct? The owner of the repo will decide?

Or it could be Git's version control can map out every variation in text, time, and creator, creating a multidimensional table (cube?) of (row, column) pairs.

I might just be lost between what commands were sent in git bash (terminal) and which are executed in the browser/github.

**Comment by chrisdaaz** [comment]
> I think I'm still lost by when a branch will be merged, or whose branch would come out on top at the end. Perhaps it's that these pull requests are not automating any later steps (such as when or which may merge with main/origin)--is that correct? The owner of the repo will decide?

Great questions! I'm not planning on merging any of the branches. I just wanted to demonstrate the process of creating a branch and making a pull request. It is indeed up to the owner of the repo to decide what to do with the pull requests. Sometimes there will be discussion about them (like here), sometimes another collaborator will checkout the branch and make commits to the branch before it is merged, and sometimes the pull request will be closed (and the branch deleted) if the changes are rejected.

> I might just be lost between what commands were sent in git bash (terminal) and which are executed in the browser/github.

Everything in github can be done throug git bash/terminal, but typically pull requests are reviewed, discussed, and merged in the github interface. github lets you test pull requests to automatically check to see if the changes will "break" the project (that's something that we'll discuss in week three/four). By default, github checks for merge conflicts (i.e. when the same file was changed on different branches and git doesn't know which branch should override the other one.

**Comment by jas58** [comment]
This clears up a lot.  Also, reading the Atlassian again: I can now see the first paragraph is the crux of the whole lesson.  (Usually, I had to read 20-50 pages and then look up a SparkNotes video to understand what was going on in college).  This is very different and welcome!
Pull = fetch+merge
Pulls are risky (because of the merge)
Push or Fetch are safer because of the branch function.  (I think.)

**Pull request merged**
